---

services:
  jupyter:
    container_name: jupyter
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - /home/delio/projects/notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
